# docker-compose.yml
version: "3.7"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"

      #SERVER_NAME: "42ghorvath"
      #MOTD: "First Peaceful World"

      #DIFFICULTY: "peaceful"

      # https://github.com/itzg/docker-minecraft-server#memory-limit
      #MEMORY: 2G

    volumes:
      - ./temp_data:/data

#docker run -e EULA=TRUE -p 25565:25565 -v /Users/ulenius/workflow/docker-bonus/srcs/02_bonus/ex02/temp_data:/data itzg/minecraft-server:latest