#!/bin/bash

docker exec spawning-pool env

# docker inspect -f \ '{{range $index, $value := .Config.Env}}{{$value}} {{end}}' spawning-pool
# docker inspect -f '{{.Config.Env}}' spawning-pool
# docker inspect -f \ '{{range $index, $value := .Config.Env}}{{println $value}}{{end}}' \ spawning-pool | grep MYSQL_

# https://stackoverflow.com/questions/34051747/get-environment-variable-from-docker-container