#!/bin/bash

docker run -dit --name Abathur -v ~/:/root -p 3000:3000 python:2-slim
docker exec Abathur pip install Flask
echo 'from flask import Flask\napp = Flask(__name__)\n@app.route("/")\ndef hello_world():\n\treturn "<h1>Hello World</h1>"' > ~/app.py
docker exec -e FLASK_APP=/root/app.py Abathur flask run --host=0.0.0.0 --port 3000

# https://pythonbasics.org/flask-tutorial-hello-world/
# https://stackoverflow.com/questions/12715834/in-flask-why-does-this-hello-world-app-work/12715896
# https://flask.palletsprojects.com/en/2.0.x/quickstart/