#!/bin/bash

docker service ls

# have to be on the manager swarm which in our case is the virtual machine
# the reason why not the school iMac because stuff said port 2377 not working that way for
# some reason, so had to make opposite way the task,
# so the manager is now our VM and there we listing the created
# services